# Generated by Django 5.2.8 on 2025-11-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('background', models.CharField(choices=[('engineering', 'Engineering'), ('arts', 'Arts/Commerce'), ('working', 'Working Professional'), ('student', 'Student')], default='student', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('work', 'Work History'), ('education', 'Education'), ('family', 'Family & Background'), ('general', 'General Awareness')], max_length=20)),
                ('expected_points', models.TextField(help_text='Key points expected in answer (from Book)')),
            ],
        ),
        migrations.CreateModel(
            name='SRTSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_text', models.TextField()),
                ('ideal_action_keywords', models.TextField(help_text="Comma separated keywords like 'jumps, saves'")),
                ('time_limit', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='WATWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('ideal_response_hint', models.TextField(help_text="Hint from Dr. Natarajan's Book")),
                ('time_limit', models.IntegerField(default=15, help_text='Time in seconds')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('WAT', 'WAT'), ('SRT', 'SRT'), ('PI', 'Interview')], max_length=10)),
                ('question_id', models.IntegerField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='responses/audio/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_api.candidate')),
            ],
        ),
    ]
