# Generated by Django 5.2.8 on 2025-11-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0002_interviewquestion_evaluation_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresponse',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
