# Generated by Django 5.2.8 on 2025-11-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0003_candidateresponse_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='background',
        ),
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_type',
            field=models.CharField(choices=[('fresher', 'Fresher'), ('internship', 'Internship Experience'), ('working', 'Working Professional')], default='fresher', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='grad_year',
            field=models.IntegerField(default=2024, help_text='e.g., 2024'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='session_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='stream',
            field=models.CharField(default='General', help_text='e.g., Computer Science, Commerce', max_length=100),
            preserve_default=False,
        ),
    ]
