# Generated by Django 5.2.8 on 2025-11-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0004_remove_candidate_background_candidate_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='category',
            field=models.CharField(choices=[('work', 'Work History'), ('education', 'Education'), ('internship', 'Internship'), ('family', 'Family & Background'), ('general', 'General Awareness')], max_length=20),
        ),
    ]
