# Generated by Django 5.2.8 on 2025-11-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0005_alter_interviewquestion_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIRQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=100)),
                ('option_b', models.CharField(max_length=100)),
                ('option_c', models.CharField(max_length=100)),
                ('option_d', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(help_text='A, B, C, or D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PPDTImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.CharField(help_text='URL or Local Path (e.g. /ppdt_1.jpg)', max_length=200)),
                ('ideal_story_theme', models.TextField(help_text='Context for AI Scoring')),
            ],
        ),
    ]
