# Generated by Django 5.2.8 on 2025-11-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0006_oirquestion_ppdtimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='category',
            field=models.CharField(choices=[('intro', 'Self Introduction'), ('work', 'Work History'), ('education', 'Education'), ('internship', 'Internship'), ('family', 'Family & Background'), ('general', 'General Awareness')], max_length=20),
        ),
    ]
