# Generated by Django 5.2.8 on 2025-11-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0007_alter_interviewquestion_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDTPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.CharField(max_length=200)),
                ('expected_qualities', models.TextField(help_text='Qualities AI should look for')),
            ],
        ),
        migrations.CreateModel(
            name='TATImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.CharField(help_text='/tat_1.jpg', max_length=200)),
                ('theme', models.TextField(help_text='Expected theme for AI scoring')),
            ],
        ),
    ]
