# Generated by Django 5.2.8 on 2025-11-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0008_sdtprompt_tatimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresponse',
            name='olq_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
