# Generated by Django 5.2.8 on 2025-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_api', '0009_candidateresponse_olq_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresponse',
            name='voice_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
